config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

product/urls.py
from django.urls import path
from .views import home, add_cart, cart_list

app_name = 'product'

urlpatterns = [
    path('', home, name='list'),
    path('add/<int:id>/', add_cart, name='add-cart'),
    path('cart/list/', cart_list, name='cart-list')
]

product/models.py
from django.db import models


class ProductModel(models.Model):
    name = models.CharField(max_length=200)
    img = models.ImageField(upload_to='product/')
    price = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

product/views.py
import random

from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import ProductModel


def home(request):
    products = ProductModel.objects.all()
    return render(request, 'home.html', context={
        'products': products
    })


def add_cart(request, id):
    cart = request.session.get('cart', [])

    if id in cart:
        cart.remove(id)
    else:
        cart.append(id)

    request.session['cart'] = cart
    return redirect('/')


def cart_list(request):
    cart = request.session.get('cart', [])
    products = ProductModel.objects.filter(id__in=cart)
    return render(request, 'cart_list.html', context={
        'products': products
    })

templates/cart_list.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="row mt-3">
        {% for product in products %}
            <div class="col-6 offset-3">
                <div class="card mb-3" style="max-width: 540px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            <img src="{{ product.img.url }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">This is a wider card with supporting text below as a natural
                                    lead-in to
                                    additional content. This content is a little bit longer.</p>
                                <p class="card-text"><small class="text-body-secondary">{{ product.price }}$</small>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

templates/home.html
{% extends 'layouts/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row mt-3">
        {% for product in products %}
            {% check_cart request product.id as check %}
            <div class="col-3">
                <div class="card" style="width: 18rem;">
                    <img src="{{ product.img.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.price }}$</p>
                        <a href="{% url 'product:add-cart' id=product.id %}" class="btn btn-primary"><i
                                class="bi
                        {% if check %}
                            bi-cart-x-fill
                        {% else %}
                            bi-cart-check-fill
                        {% endif %}
                        "></i> add to card</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        <h3>{{ request.session.items }}</h3>
    </div>
{% endblock %}

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">

    {% block extra_css %}
    {% endblock %}
</head>
<body>
{% include 'layouts/navbar.html' %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>

{% include 'layouts/footer.html' %}
{% block extra_js %}
{% endblock %}
<script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>
</body>
</html>

templates/layouts/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/layouts/navbar.html
{% load my_tags %}
{% count_cart request as count %}
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'product:cart-list' %}"><i class="bi bi-cart-check-fill"></i> {{ count }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>